### ISSUE TITLE
Paginator breaks on d.net nightly

### ISSUE THREAD

**Issue by LazyBoot** [PassiveModding/Discord.Addons.Interactive#5]
Using discord.net 2.2.0-dev-20191025.3
and Discord.Addons.PassiveInteractive 2.0.4
```
A ReactionAdded handler has thrown an unhandled exception.
System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task Discord.IUserMessage.RemoveReactionAsync(Discord.IEmote, Discord.IUser, Discord.RequestOptions)'.
   at Discord.Addons.Interactive.PaginatedMessageCallback.HandleCallbackAsync(SocketReaction reaction)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Discord.Addons.Interactive.PaginatedMessageCallback.HandleCallbackAsync(SocketReaction reaction)
   at Discord.Addons.Interactive.InteractiveService.HandleReactionAsync(Cacheable`2 message, ISocketMessageChannel channel, SocketReaction reaction)
   at Discord.EventExtensions.InvokeAsync[T1,T2,T3](AsyncEvent`1 eventHandler, T1 arg1, T2 arg2, T3 arg3)
   at Discord.WebSocket.DiscordSocketClient.TimeoutWrap(String name, Func`1 action)
```

**Comment by Cyber-Garret** [comment]
In Discord.Addons.Interactive update package reference Discord.Net.WebSocket and Discord.Net.Commands to 2.2.0 for fixing issue
